name: Build Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: autoreconf
      run: autoreconf --install

    - name: configure
      run: ./configure

    - name: Building native
      run: make
      
    - name: Copy native binaries to native dir
      run: |
        mkdir native
        cp ./src/file ./native/file
        cd native
        mkdir .libs
        cd ..
        cp -Lr ./src/.libs/file ./native/.libs/file
        cp -Lr ./src/.libs/libmagic.so.* ./native/.libs/

    - uses: mymindstorm/setup-emsdk@v11

    - name: Verify Emscripten
      run: emcc -v
      
    - name: Build WASM configure
      run: emconfigure ./configure

    - name: patch script to use native file to compile magic.mgc
      run: sed -i 's/file\/src\/.libs/file\/native\/.libs/g' ./native/file

    - name: Make WASM dir
      run: mkdir wasm

    - name: Run build script file
      run: |
         chmod +x ./build_wasm.sh
         ./build_wasm.sh
      shell: bash
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          wasm/libmagic.wasm
          wasm/libmagic.js
